Added pin cluster list
scures/dashboard pull request #2
Opened 2023-09-07 11:05 UTC by bisht-richa

Fixes https://github.com/rancher/dashboard/issues/9587

Allow the user to pin a cluster by clicking it
Store this configuration of the saved clusters in the same format as we get it here

==== On hover =====
![Screenshot 2023-09-07 at 12 49 27](https://github.com/rancher/dashboard/assets/18264463/2f7c0f89-c547-44ea-86b9-6e24d2f6d1aa)

==== Close =====
![Screenshot 2023-09-07 at 12 46 26](https://github.com/rancher/dashboard/assets/18264463/6f5477ca-6221-417b-9439-4144616ff931)

==== Open =====
![Screenshot 2023-09-07 at 12 46 36](https://github.com/rancher/dashboard/assets/18264463/acc5bc6e-fa2d-4b4d-9b5c-5d9a1abd549a)

2023-09-07 11:18 UTC, scures commented on shell/components/ClusterIconMenu.vue
>        <!-- {{ cluster.badge.iconText }} -->
Can we remove this line?

2023-09-07 11:18 UTC, scures commented on shell/components/ClusterIconMenu.vue
> -    <!-- eslint-enable -->
And this one

2023-09-07 11:46 UTC, bisht-richa commented on shell/components/ClusterIconMenu.vue
> -    <!-- eslint-enable -->
This one is not there :)

2023-09-07 12:28 UTC, scures commented on shell/components/nav/Pinned.vue
> +    transform: scaleX(-1);
I'm happy to see this worked! :P

2023-09-07 12:29 UTC, scures commented on shell/components/nav/TopLevelMenu.vue
> +      const sorted = sortBy(out, ['ready:desc', 'ready']);
This is the same thing I had before, we can improve it by removing the extra `ready` and have only `['ready:desc', 'label']`

2023-09-07 15:03 UTC, richard-cox requested changes
- to discuss - i think the user should still be able to pin clusters that aren't ready
- clusters that are pinned should always show regardless of window size. at the moment they will be collapsed as per non-pinned clusters

2023-09-07 15:03 UTC, richard-cox commented on cypress/e2e/tests/navigation/side-nav/main-side-menu.spec.ts
> +    burgerMenuPo.pinClustersList().should('exist');
we should also test unpinning. that'll also leave the ui in a state similar to when the test started

2023-09-07 15:03 UTC, richard-cox commented on shell/store/type-map.js
> +  isPinned(state, getters, rootState, rootGetters) {
isPinned, addPin and removePin should all be named something more specific. i think we can just go with isClusterPinned, pinCluster, unpinCluster.

2023-09-07 15:03 UTC, richard-cox commented on shell/store/type-map.js
> +  isPinned(state, getters, rootState, rootGetters) {
the three convenience methods should either be in the `MANAGEMENT.CLUSTER` model (isPinned, pin, unpin). if we want to keep them generic in case we want to pin other resource types in the future the methods should be in the `prefs` store

2023-09-07 15:03 UTC, richard-cox commented on shell/store/prefs.js
> +export const PIN_TYPES = create('fav-type', [], { parseJSON });
`PIN_TYPES` --> `PINNED_CLUSTERS`

2023-09-07 15:03 UTC, richard-cox commented on shell/store/prefs.js
> +export const PIN_TYPES = create('fav-type', [], { parseJSON });
`fav-type` --> `pinned-clusters`

2023-09-07 15:03 UTC, richard-cox commented on shell/components/nav/TopLevelMenu.vue
> +        const pin = this.pinnedClusters.some((c) => c === x.id);
some --> find

2023-09-07 15:03 UTC, richard-cox commented on shell/components/nav/Pinned.vue
> +export default {
Could you had a super brief description for what this is used for (i.e. the pin action, rather than the pin in the icon)

2023-09-07 15:09 UTC, richard-cox commented
in addition, `cluster-badge-logo` has a `padding-top: 2px` which makes the acronym not vertically centred

2023-09-08 13:32 UTC, richard-cox commented on shell/store/type-map.js
> +  isPinned(state, getters, rootState, rootGetters) {
Resolved via patch file

2023-09-08 13:32 UTC, richard-cox commented on shell/store/type-map.js
> +  isPinned(state, getters, rootState, rootGetters) {
Resolved via patch file

2023-09-08 13:32 UTC, richard-cox commented on shell/store/prefs.js
> +export const PIN_TYPES = create('fav-type', [], { parseJSON });
Resolved

2023-09-08 13:32 UTC, richard-cox commented on shell/store/prefs.js
> +export const PIN_TYPES = create('fav-type', [], { parseJSON });
Resolved

2023-09-08 13:32 UTC, richard-cox commented on shell/components/nav/TopLevelMenu.vue
> +        const pin = this.pinnedClusters.some((c) => c === x.id);
Line removed. Comment resolved

2023-11-15 11:28 UTC, closed without merging